"""UU automation settings and template locations."""

from pathlib import Path

from starrail_auto.settings import EVIDENCE_DIR, TEMPLATES_DIR

UU_EXE = Path(r"D:\2_Software\4_Games\Netease\UU\uu_launcher.exe")
DEBUG_DIR = EVIDENCE_DIR

TPL_STEP_1 = TEMPLATES_DIR / "uu_01.png"
TPL_STEP_2 = TEMPLATES_DIR / "uu_02.png"
TPL_STEP_3 = TEMPLATES_DIR / "uu_03.png"
TPL_UPDATE_NOTICE = TEMPLATES_DIR / "uu_update_notice.png"
TPL_UPDATE_CONFIRM = TEMPLATES_DIR / "uu_update_confirm.png"
TPL_UPDATE_CLOSE = TEMPLATES_DIR / "uu_update_close.png"

UU_WINDOW_TIMEOUT = 30
WINDOW_CHECK_INTERVAL = 1
IMAGE_SEARCH_TIMEOUT = 30
IMAGE_RETRY_INTERVAL = 0.25
IMAGE_CONFIDENCE = 0.8
STEP_1_INITIAL_DELAY = 3.0
STEP_1_TIMEOUT = 10.0
STEP_2_TIMEOUT = 5.0
REUSE_CONFIRM_TIMEOUT = 3.0
POST_MOVE_DELAY = 0.5
POST_CLICK_WAIT = 20
CONFIRM_TIMEOUT = 30
STOP_ACCELERATION_TIMEOUT = 10.0
UU_RESTART_DELAY = 5.0
UU_MINIMIZE_BEST_EFFORT_TIMEOUT = 5.0
UU_POPUP_DETECT_TIMEOUT = 0.8
UU_POPUP_ACTION_TIMEOUT = 2.0
UU_POPUP_SETTLE_DELAY = 0.5
UU_POPUP_MAX_DISMISSALS = 3
UU_STARTUP_MAX_RESTARTS = 3
EXPECTED_PRIMARY_SCREEN_SIZE = (2560, 1440)

UU_WINDOW_KEYWORDS = ("uu", "网易uu", "uu加速器")
UU_PROCESS_KEYWORDS = ("uu", "uuaccelerator", "uulauncher")
UU_UPDATE_POPUP_ACTIONS = (
    ("confirm", TPL_UPDATE_CONFIRM),
    ("close", TPL_UPDATE_CLOSE),
)
